### ISSUE TITLE
How to use this with fuse box file

### ISSUE THREAD

**Issue by SanthoshDhandapani** [fuse-box-contrib/fuse-box-yaml#1]
Thanks for the plugin. Any example for using this plugin ?

**Comment by maximkott** [comment]
Hi, you can use it like this

```js
const {YAMLPlugin} = require('fuse-box-yaml')
fsb.FuseBox.init({
  plugins: [
    YAMLPlugin(),
  ]
})
```

**Comment by SanthoshDhandapani** [comment]
Hi @maximkott, I saw this. Could you explain with an example by parsing a yaml file using this plugin.

**Comment by maximkott** [comment]
Simply require the .yml file. Let's say you have a file like this:

```yml
foo: bar
```

No in js you can import it directly:

```js
import * as data from './data.yml'

console.log(data.foo)
```

**Comment by SanthoshDhandapani** [comment]
Got it. Thank you @maximkott
